spring.thymeleaf.cache=false
spring.datasource.url=jdbc:postgresql://localhost:5432/citas
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# Le dice a Spring: "No toques la estructura de la BD, yo la manejo con mis scripts"
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true